#!/bin/sh
### BEGIN INIT INFO
# Provides:          jobarchive
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Slurm /var/slurm/jobscript_archive exporter
### END INIT INFO

# normal w/o debug=0 logging
PROG="/usr/local/jobarchive/job_archive"
### NOTE: build from your local github subdirectory -> job_archive
# with debug=1 logging auto turned on
#PROG="/usr/local/jobarchive/job_archive -d"

PIDFILE=/var/run/jobarchive/jobarchive.pid
LOGFILE=/var/log/jobarchive/jobarchive.log
RUNAS=slurm

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$PROG &>> \"$LOGFILE\" & echo \$!"
  echo su - $RUNAS -c "$CMD"> "$PIDFILE"
  su - $RUNAS -c "$CMD"> "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
